language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - compiler: gcc-7
      os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - python3.6-dev
            - python3.6-venv
            - gcc-7
            - g++-7
            - libhdf5-serial-dev
      env: GCC=7 PYTHON=python3.6
    - compiler: gcc-7
      os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - python3.5-dev
            - python3.5-venv
            - gcc-7
            - g++-7
            - libhdf5-serial-dev
      env: GCC=7 PYTHON=python3.5
    - compiler: clang-5
      os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            # we install gcc in the clang builds to get an updated libstd++
            - gcc-7
            - g++-7
            - python3.6-dev
            - python3.6-venv
            - libhdf5-serial-dev
      env: CLANG=5.0 PYTHON=python3.6 PATH=/usr/local/clang-5.0.0/bin:$PATH
    - compiler: clang-5
      os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            # we install gcc in the clang builds to get an updated libstd++
            - gcc-7
            - g++-7
            - python3.5-dev
            - python3.5-venv
            - libhdf5-serial-dev
      env: CLANG=5.0 PYTHON=python3.5 PATH=/usr/local/clang-5.0.0/bin:$PATH

install:
  - source etc/ci-install.sh

before_script:
  - ${CXX} --version
  - ${PYTHON} --version

script:
  - make -j8 $(if [ -z "$GCC" ];then echo test;else echo coverage;fi)

notifications:
  email: false
