language: python
dist: xenial
sudo: true

python:
    - "2.7"
    - "3.6"
    - "3.7-dev"

env:
  - CXX=g++-8 CC=gcc-8
  - CXX=clang++-6.0 CC=clang-6.0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - gcc-8
      - g++-8
      - clang-6.0
      - libhdf5-serial-dev

install:
  - source etc/ci-install.sh

before_script:
  - ${CXX} --version
  - ${CC} --version
  - python --version

script:
  - HDF5_INCLUDE_PATH=/usr/include/hdf5/serial/ HDF5_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/hdf5/serial make -j8 $(if [ ${CXX} --version | grep 'GCC' ];then echo coverage;else echo test;fi)

notifications:
  email: false
